server:
  port: 8016
spring:
  application:
    name: microservice-sidecar
eureka:
  client:
    service-url:
      defaultZone: http://zhang:123@localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    com.netflix: debug
    

sidecar:
  port: 8060  #此处配置的要调用的微服务的端口
  health-uri: http://localhost:8000/health.json  #要调用的微服务的地址