spring:
  application:
    name: microservice-consumer-movie-feign-with-hystrix
    
server:
  port: 7903
  
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://zhang:123@localhost:8761/eureka
  instance:
    prefer-ip-address: true

# 启用hystrix
feign:
  hystrix:
    enabled: true

# hystrix 请求超时时间 默认是1s
hystrix:
  command: 
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500000000

#  client:
#    config:
#      default:
#        connectTimeout: 2000
#        readTimeout: 3000
#        loggerLevel: basic
#      # 会覆盖上面的全局配置FeignClientFactoryBean.configureFeign(),切回覆盖下面的ribbon配置
#      microservice-provider-user:
#        connectTimeout: 3000
#        readTimeout: 4000
    
# 优先级  
  # properties > @Configuration
  # feign service level > feign default > ribbon service level > ribbon global
    

# 全局配置
#ribbon:
#  OkToRetryOnAllOperations: true # 对所有操作请求都进行重试
#  MaxAutoRetries: 3    # 对当前实例的重试次数
#  MaxAutoRetriesNextServer: 2 # 切换实例的重试次数

# 服务级别配置(会覆盖全局配置)
microservice-provider-user: 
  ribbon:
    OkToRetryOnAllOperations: false # 对所有操作请求都进行重试(默认get请求对所有异常进行重试，post请求只对ConnectException异常进行重试)
    MaxAutoRetries: 2    # 对当前实例的重试次数
    MaxAutoRetriesNextServer: 0 # 切换实例的重试次数
    ReadTimeout: 5000  #数据读取超时时间
    ConnectTimeout: 3000 # 连接超时时间      
    
          