spring:
  application:
    name: microservice-consumer-movie-ribbon
server:
  port: 8010
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://zhang:123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    
# 服务级别配置，优先级大于下面全局配置
microservice-provider-user: 
  ribbon: 
    MaxAutoRetries: 3
    
# 全局配置，适用于所有服务
ribbon:
  OkToRetryOnAllOperations: true # 是否对所有请求都进行重试
  MaxAutoRetries: 1     # 每个实例重试次数
  MaxAutoRetriesNextServer: 2   # 重试切换实例次数
  ConnectTimeout: 250
  ReadTimeout: 300
  retryableStatusCodes: 503,500 # 这里不配置其实也可以，不配置的时候，仅仅当请求服务实例报错的时候重试，配置了的时候，当请求服务实例出现这里指定的状态，也会重试
    