spring:
  application:
    name: microservice-consumer-movie-feign-with-hystrix
server:
  port: 7902
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://zhang:123@localhost:8761/eureka
  instance:
    prefer-ip-address: true

feign.hystrix.enabled: true