spring:
  application:
    name: microservice-consumer-movie-feign-with-hystrix
    
server:
  port: 7903
  
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://zhang:123@localhost:8761/eureka
  instance:
    prefer-ip-address: true

# 开启 hystrix功能
feign:
  hystrix:
    enabled: true
    
    
# hystrix 请求超时时间 默认是1s
hystrix:
  command: 
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000  #设置hystrix请求超时时间，默认1s
      
# ribbon中可以访问,feign中不起作用(/actuator/hystrix.stream), 要额外配置 ??? 
# 该配置会导致/actuator/info失效
#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream
            