spring:
  application:
    name: microservice-consumer-movie-feign-with-hystrix
    
server:
  port: 7903
  
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://zhang:123@localhost:8761/eureka
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true
    
    
# hystrix 请求超时时间 默认是1s
hystrix:
  command: 
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500000000
            