spring:
  application:
    name: microservice-consumer-movie
  cloud:
    loadbalancer:
      retry:
        enabled: false
    
server:
  port: 7903
  
  
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://zhang:123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    
    
feign:
  httpclient:
    connection-timeout: 10000000
