server:
  port: 8080

spring:
  cloud:
    config:
      server:
        svn:
          uri: http://192.168.23.30:7070/svn/epay-personal/doc/配置/SpringCloudConfig/
          search-paths:
          - '{application}'
          username: zhangzhigang
          password: BeK8SzyS3GYC
        default-label: config
  profiles:
    active: subversion
  application:
    name: microservice-config-server-eureka

ribbon:
  eager-load:
    enabled: true

eureka: 
  client:
    serviceUrl:
       defaultZone: http://zhang:123@localhost:8761/eureka
  instance:
    prefer-ip-address: true