spring:
  application:
    name: microservice-consumer-movie-ribbon-with-hystrix
  cloud:
    circuitbreaker:
      hystrix:
        enabled: true
    
server:
  port: 8011
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://zhang:123@localhost:8761/eureka
  instance:
    prefer-ip-address: true

# hystrix 请求超时时间 默认是1s
hystrix:
  command: 
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000000
            
