spring:
  application:
    name: microservice-consumer-movie
  cloud:
    loadbalancer:
      retry:
        enabled: false
    
server:
  port: 7903
  
  
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://zhang:123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    
    
feign:
  httpclient:
    connection-timeout: 10000000
    
# 全局配置
#ribbon:
#  OkToRetryOnAllOperations: true # 对所有操作请求都进行重试
#  MaxAutoRetries: 3    # 对当前实例的重试次数
#  MaxAutoRetriesNextServer: 2 # 切换实例的重试次数

# 服务级别配置(会覆盖全局配置)
microservice-provider-user: 
  ribbon:
    OkToRetryOnAllOperations: false # 对所有操作请求都进行重试(默认get请求对所有异常进行重试，post请求只对ConnectException异常进行重试)
    MaxAutoRetries: 2    # 对当前实例的重试次数
    MaxAutoRetriesNextServer: 0 # 切换实例的重试次数
    ReadTimeout: 5000  #数据读取超时时间
    ConnectTimeout: 3000 # 连接超时时间
    
