spring: 
  security:
    basic:
      enabled: true
    user:
      name: zhang
      password: 123
      
server:
  port: 8761
  
eureka:
  client:
    register-with-eureka: false #eureka 单机模式
    fetch-registry: false #eureka 单机模式
    service-url:
      defaultZone: http://zhang:123@localhost:8761/eureka
#  server:
    #自我保护模式开启，当提供者掉线，服务端不会从列表中移除提供者
#    enable-self-preservation: true # 关闭自我保护模式，默认打开
#    eviction-interval-timer-in-ms: 3000 # 服务端剔除失效服务间隔,默认60000
#  dashboard:
#    path: dashboard  #配置eureka控制台地址为http://ip:port/dashboard(默认是http://ip:port)
