server:
  port: 8080
  

spring:
  cloud:
    config:
      server:
        svn:
          # 访问：http://localhost:8080/{application}/{profile}
          # /SpringCloudConfig/config/local/local-dev.yml
          # /SpringCloudConfig/config/simple/simple-dev.yml
          # 注意：local-dev.yml必须放在local文件夹下面，否则访问不到，并且只支持一层目录结构(local)
          uri: http://192.168.23.30:7070/svn/epay-personal/doc/配置/SpringCloudConfig/
          search-paths:
          - '{application}'
          username: zhangzhigang
          password: BeK8SzyS3GYC
        # git默认分支为master,svn默认分支为trunk
        default-label: config
  profiles:
    # 必须配置 默认使用git
    active: subversion
    
 
