server:
  port: 8080
  

spring:
  cloud:
    config:
      server:
        svn:
          uri: http://192.168.23.30:7070/svn/epay-personal/doc/配置/SpringCloudConfig/config/local
          repos: # svn 没有这种特性
          username: zhangzhigang
          password: BeK8SzyS3GYC
        # git默认分支为master,svn默认分支为trunk
        default-label: config
  profiles:
    # 必须配置 默认使用git
    active: subversion
    
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://git.oschina.net/it-much/config-repo-51cto-video #全局配置，当下面都不匹配时，会用这个文件配置
#          repos:
#            simple: https://git.oschina.net/it-much/simple
#            special:
#              pattern: special*/dev*,special*/test*
#              uri: https://git.oschina.net/it-much/special
    
 
