server:
  port: 8762
  
spring:
  profiles: peer2
  security:
    basic:
      enabled: true
    user:
      name: zhang
      password: 123
      
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://zhang:123@peer1:8761/eureka/,http://zhang:123@peer3:8763/eureka/
