server:
  port: 8761
  
spring:
  profiles: peer1
  security:
    basic:
      enabled: true
    user:
      name: zhang
      password: 123
      
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
       defaultZone: http://zhang:123@peer2:8762/eureka/,http://zhang:123@peer3:8763/eureka/
