server:
  port: 8013
spring:
  application:
    name: microservice-gateway-zuul-fallback
eureka:
  client:
    service-url:
      defaultZone: http://zhang:123@localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    com.netflix: debug