server:
  port: 8080

security:
  basic:
    enabled: true
  user:
    name: zhang
    password: 123

spring:
  cloud:
    config:
      server:
        svn:
          uri: http://192.168.23.30:7070/svn/epay-personal/doc/配置/SpringCloudConfig
          username: zhangzhigang
          password: BeK8SzyS3GYC
          search-paths:
          - '{application}'
        # git默认分支为master,svn默认分支为trunk
        default-label: config
  profiles:
    # 必须配置 默认使用git
    active: subversion